ARG PYTHON_VERSION=3.12-alpine  # Set default Python version
FROM python:$PYTHON_VERSION      # Use the specified Python version as base image

# Copy project files into container
COPY . /workspace

# Set working directory
WORKDIR /workspace

# Install Python packages (if any)
# RUN pip install -r requirements.txt
